package main

import (
	"fmt"
	"../mapreduce"
	"os"
	"strings"
	"strconv"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	f := func(c rune) bool {
		return !unicode.IsLetter(c)
	}
	words:=strings.FieldsFunc(value, f)
	wc:=make(map[string]int)
	for _,word:=range words {
		count,ok:=wc[word]
		if ok {
			count=count+1
			wc[word]=count
		} else {
			wc[word]=1
		}
	}

	kvs:=make([]mapreduce.KeyValue,0)
	for key,value:=range wc {
		kvs=append(kvs,mapreduce.KeyValue{key,strconv.Itoa(value)})
	}
	return kvs
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	countForKey:=0
	for _,countStr:=range values {
		count,err:=strconv.Atoi(countStr)
		if err!=nil {
			panic(err)
		}
		countForKey+=count
	}

	return strconv.Itoa(countForKey)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
